name: 🐞Bug report
description: Report a bug related for the WordPress plugin.
title: "[slymetrics] "
labels: bug
assignees:
  - slydlake

body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report! Please fill out the fields below.
        Important: The issue title should start with the plugin name in square brackets, e.g. `[slymetrics] Crash on startup`.

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: Describe how to reproduce the issue.
      placeholder: |
        1. Install the plugin
        2. Activate the plugin
        3. Observe error logs
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen.

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: What actually happened (include logs or error messages).

  - type: textarea
    id: configuration_files
    attributes:
      label: Configuration files (optional)
      description: Paste relevant parts of your configuration files here or provide a Gist/URL.

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: WordPress logs...
